import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'
import Layout from '../components/Layout'
import { store } from '../store'
import '../styles/globals.css'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Layout>
        <Head>
          <title>Audio Ecommerce - Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  )
}
